добавил практику
Kirill-sudar/JavaScript- pull request #1
Opened 2020-04-08 11:25 UTC by Kirill-sudar

2 задачи

2020-04-08 19:10 UTC, smartianin requested changes

2020-04-08 19:10 UTC, smartianin commented on main.js
> +  let arg1=prompt('Введите первый аргумент',arg1);
не пользуйся ни prompt, ни alert –– это бесполезные методы, достаточно просто указать параметр

2020-04-08 19:10 UTC, smartianin commented on main.js
> +function min(arg1,arg2) {
перепиши функцию на тернарник, заодно будет тебе больше практики, и сама функция будет выглядеть локаничней

2020-04-08 19:10 UTC, smartianin commented on main.js
> +  return function() {
Где есть возможность писать arrow function, пиши arrow function

2020-04-08 19:10 UTC, smartianin commented on main.js
> +function makeCounter() {
А теперь, сделай счетчик Глобальным

2020-04-08 19:10 UTC, smartianin commented on main.js
> +function makeCounter() {
чтобы вызов каждого инстанса увеличивал значение каунтера

2020-04-13 11:20 UTC, smartianin requested changes

2020-04-13 11:20 UTC, smartianin commented on main.js
> +function min(arg1,arg2){
`let min = (arg1, arg2) => arg1 < arg2 ? arg1 : arg2;`

Функция в одну строчку выглядит куда приятней, правда?))

Для практики напиши подобную функцию max

2020-04-13 11:20 UTC, smartianin commented on main.js
> +function makeCounter(){
Хорошо. А теперь напиши глобальный счетчик. И старайся в местах где имеет смысл использовать arrow functions

2020-04-14 20:49 UTC, Kirill-sudar commented on main.js
> +function min(arg1,arg2){
я вроде и написал так как ты ,может не то скопировал ,странно

2020-04-14 20:51 UTC, Kirill-sudar commented on main.js
> +function min(arg1,arg2){
ну да,в моем файлу написано как у тебя только не=> ,а =

2020-04-14 20:52 UTC, Kirill-sudar commented on main.js
> +function makeCounter(){
//Напишите функцию min, принимающую два аргумента, и возвращающую минимальный из них;//Напишите функцию min, принимающую два аргумента, и возвращающую минимальный из них;
function max(arg1,arg2){
  let arg1=('Введите первый аргумент');
  let arg2=('Введите второй аргумент');
  let result =(arg1>arg2)?arg1:arg2;
}

//Напиши функцию-счётчик, которая считает свои вызовы и возвращает их текущее число.
function makeCounter(){
  let count=1;
  return function(){
    count++
  }
}
challengeFunction=makeCounter();
console.log(challengeFunction);

2020-04-24 07:42 UTC, smartianin requested changes

2020-04-24 07:42 UTC, smartianin commented on main.js
> + makeCounter=()=>function() {return currentCount++;}
```suggestion
 makeCounter = () => () => ++currentCount;
```

2020-04-24 07:42 UTC, smartianin commented on main.js
> + var currentCount = 1;
```suggestion
 var currentCount = 0;
```

2020-06-04 12:34 UTC, closed without merging